"""Intent handlers package — re-exports all public handlers for backward compatibility."""

from ._helpers import (
    ALICE_RESPONSE_MAX_LENGTH,
    MAX_BRIEFING_TASKS,
    _apply_task_filters,
    _auth_required_response,
    _find_active_task,
    _format_date,
    _format_priority_label,
    _format_priority_short,
    _format_task_context,
    _format_task_line,
    _format_ticktick_dt,
    _gather_all_tasks,
    _get_access_token,
    _get_user_tz,
    _invalidate_task_cache,
    _is_only_stopwords,
    _reset_project_cache,
    _TaskMatch,
    _to_user_date,
    _truncate_response,
)
from .briefings import (
    _build_evening_briefing_text,
    _build_morning_briefing_text,
    handle_evening_briefing,
    handle_morning_briefing,
)
from .checklists import (
    handle_add_checklist_item,
    handle_check_item,
    handle_delete_checklist_item,
    handle_show_checklist,
)
from .misc import handle_goodbye, handle_help, handle_help_topic, handle_unknown, handle_welcome
from .projects import handle_create_project, handle_list_projects, handle_project_tasks
from .subtasks import handle_add_subtask, handle_list_subtasks
from .tasks import (
    _build_create_task_response,
    handle_add_reminder,
    handle_complete_confirm,
    handle_complete_reject,
    handle_complete_task,
    handle_create_recurring_task,
    handle_create_task,
    handle_delete_confirm,
    handle_delete_reject,
    handle_delete_task,
    handle_edit_confirm,
    handle_edit_reject,
    handle_edit_task,
    handle_list_tasks,
    handle_overdue_tasks,
    handle_search_task,
)

__all__ = [
    "ALICE_RESPONSE_MAX_LENGTH",
    "MAX_BRIEFING_TASKS",
    "_TaskMatch",
    "_apply_task_filters",
    "_auth_required_response",
    "_build_create_task_response",
    "_build_evening_briefing_text",
    "_build_morning_briefing_text",
    "_find_active_task",
    "_format_date",
    "_format_priority_label",
    "_format_priority_short",
    "_format_task_context",
    "_format_task_line",
    "_format_ticktick_dt",
    "_gather_all_tasks",
    "_get_access_token",
    "_get_user_tz",
    "_invalidate_task_cache",
    "_is_only_stopwords",
    "_reset_project_cache",
    "_to_user_date",
    "_truncate_response",
    "handle_add_checklist_item",
    "handle_add_reminder",
    "handle_add_subtask",
    "handle_check_item",
    "handle_complete_confirm",
    "handle_complete_reject",
    "handle_complete_task",
    "handle_create_project",
    "handle_create_recurring_task",
    "handle_create_task",
    "handle_delete_checklist_item",
    "handle_delete_confirm",
    "handle_delete_reject",
    "handle_delete_task",
    "handle_edit_confirm",
    "handle_edit_reject",
    "handle_edit_task",
    "handle_evening_briefing",
    "handle_goodbye",
    "handle_help",
    "handle_help_topic",
    "handle_list_projects",
    "handle_list_subtasks",
    "handle_list_tasks",
    "handle_morning_briefing",
    "handle_overdue_tasks",
    "handle_project_tasks",
    "handle_search_task",
    "handle_show_checklist",
    "handle_unknown",
    "handle_welcome",
]
